/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/modeld.glb 
Author: Elisey (https://sketchfab.com/dwelfster)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-zergling-95bcd72dac2d4be6a7085a7810f55838
Title: Human-zergling
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useCharacterAnimations } from '../context/CharacterAnimations'

export function Character(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/human.glb')
  const { actions, names } = useAnimations(animations, group)
  const { setAnimations } = useCharacterAnimations();
  console.log(names);

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {
    actions[names[0]].reset().fadeIn(1).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
          <group name="0289dc7f39b94861a54b3cd3dec324ebfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="BAse" scale={20}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_47" scale={20} />
                    <skinnedMesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Scene_-_Root']} skeleton={nodes.Object_48.skeleton} />
                  </group>
                </group>
                <group name="1" scale={20} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/human.glb')
