/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/modelc.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from '../context/CharacterAnimations'

export function Soldierc(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/modelc.glb')
  const { actions, names } = useAnimations(animations, group)
  const { setAnimations } = useCharacterAnimations();
  console.log(names);

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  // useEffect(() => {
  //   actions[names[0]].reset().fadeIn(0.5).play();
  // }, []);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SM_Chr_Eyebrows_01.geometry} material={materials.PolygonKids_Material_04_B} />
      <mesh geometry={nodes.SM_Chr_Eyes_Female_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Eyes_Male_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Adventure_01_1.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Alien_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Alien_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Android_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Ballerina_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Cardboard_Robot_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_CargoShorts_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Casual_04.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Cheerleader_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Cowboy_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Cowboy_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Demon_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Doctor_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Dress_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Eastern_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Eastern_Skirt_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Elf_Warrior_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Exercise_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Exercise_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Explorer_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Farmer_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Fat_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Fat_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Footballer_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Geisha_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Ghost_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Goblin_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Goblin_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_HolidayElf_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Hoodie_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Hoodie_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Hoodie_03.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_JungleKid_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Karate_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Knight_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Magician_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Maid_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Mummy_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Nerd_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Ninja_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Onesie_Bunny_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Onesie_Cat_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Onesie_Dino_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Onesie_Tiger_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Overalls_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Overalls_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Overalls_Dress_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Pajamas_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Peasant_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Pig_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Pilot_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Pirate_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Pirate_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_PlaidShirt_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_PoliceOfficer_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Prince_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Princess_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_PufferVest_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Punk_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Raincoat_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Raincoat_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Robber_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Robot_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Samurai_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Schoolboy_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Schoolboy_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Schoolgirl_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Schoolgirl_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Scifi_Casual_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Scifi_Spacesuit_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Scout_Shorts_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Scout_Skirt_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_ShirtDress_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Skater_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Skeleton_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_SnowJacket_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Spacesuit_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Summer_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Superhero_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Superhero_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Survivor_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Survivor_Armoured_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Survivor_Vest_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Sweater_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Sweater_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Sweater_Dress_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Swimwear_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Swimwear_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Tracksuit_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Troll_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Trucker_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Viking_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Viking_02.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Werewolf_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Wetsuit_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_WinterCoat_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Witch_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Wizard_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Zombie_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <mesh geometry={nodes.SM_Chr_Kid_Zombie_Dress_01.geometry} material={materials.PolygonKids_Material_01_A} />
      <group position={[0, 54.368, 0]} rotation={[1.421, Math.PI / 2, 0]}>
        <group position={[7.916, -0.656, 0]} rotation={[Math.PI, 0, -0.2]}>
          <group position={[11.763, 1.826, 0]} rotation={[-Math.PI, 0, -0.196]}>
            <group position={[9.266, 1.674, 0]} rotation={[Math.PI, 0, -0.223]}>
              <group position={[9.36, -0.057, 0]} rotation={[0, 0, -0.083]}>
                <group position={[7.553, -0.216, 0]} rotation={[Math.PI / 2, 0.16, -Math.PI / 2]}>
                  <mesh geometry={nodes.SM_Chr_Kid_Face_01.geometry} material={materials.PolygonKids_Material_Face_01_A} position={[0, 2.79, 10.98]} />
                  <mesh geometry={nodes.SM_Chr_Kid_Face_Freckles_01.geometry} material={materials.PolygonKids_Material_Face_Freckles_01_A} position={[0, 2.79, 11.06]} />
                  <mesh geometry={nodes.SM_Chr_Kid_Robot_Face_01.geometry} material={materials.Default_Material} />
                  <mesh geometry={nodes.SM_Chr_Hair_Fringe_02.geometry} material={materials.PolygonKids_Material_04_B} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/modelc.glb')
