/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf 
Author: PixartistLilack (https://sketchfab.com/PixartistLilack)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/n-anniversary-40-098effb437a2471d8ef55eb9f83ecbb1
Title: N_Anniversary_40
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useCharacterAnimations } from '../context/CharacterAnimations'

export function Woman(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Woman/scene.gltf')
  const { actions, names } = useAnimations(animations, group)
  const { setAnimations } = useCharacterAnimations();
  console.log(names);

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="N_Anniversary_40fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature447" scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_173" scale={100} />
                    <skinnedMesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials['M_ch0089_40_n_body.001']} skeleton={nodes.Object_174.skeleton} />
                    <skinnedMesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials['M_ch0089_40_n_mouth.001']} skeleton={nodes.Object_175.skeleton} />
                    <skinnedMesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials['M_ch0089_40_n_hair.001']} skeleton={nodes.Object_176.skeleton} />
                    <skinnedMesh name="Object_177" geometry={nodes.Object_177.geometry} material={materials['M_ch0089_40_n_skin.001']} skeleton={nodes.Object_177.skeleton} />
                    <skinnedMesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials['M_ch0089_40_n_face.001']} skeleton={nodes.Object_178.skeleton} />
                  </group>
                </group>
                <group name="N_Anniversary_EX" scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Woman/scene.gltf')
